apiVersion: batch/v1
kind: Job
metadata:
  name: seed-data
  labels:
    app: seed-data
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: seed-data
    spec:
      restartPolicy: Never
      containers:
      - name: seed-data
        image: seed-data:local
        imagePullPolicy: Never
        command:
          - /bin/sh
          - -c
          - |
            set -e
            ab -n 1000 -c 50 -p posta -T "application/x-www-form-urlencoded" http://vote:5000/
            ab -n 1000 -c 50 -p postb -T "application/x-www-form-urlencoded" http://vote:5000/
            ab -n 1000 -c 50 -p posta -T "application/x-www-form-urlencoded" http://vote:5000/
