apiVersion: batch/v1
kind: Job
metadata:
  name: seed-data
  labels:
    app: seed-data
spec:
  backoffLimit: 2
  template:
    metadata:
      name: seed-data
      labels:
        app: seed-data
    spec:
      restartPolicy: Never
      containers:
      - name: seed-data
        image: europe-west3-docker.pkg.dev/tuto-devops-490710/voting-image/seed-data:latest
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - |
            set -e
            ab -n 1000 -c 50 -p posta -T "application/x-www-form-urlencoded" http://vote:5000/
            ab -n 1000 -c 50 -p postb -T "application/x-www-form-urlencoded" http://vote:5000/
            ab -n 1000 -c 50 -p posta -T "application/x-www-form-urlencoded" http://vote:5000/
      # optionnel : limiter ressources si besoin
      # resources:
      #   requests:
      #     cpu: "100m"
      #     memory: "128Mi"
      #   limits:
      #     cpu: "200m"
      #     memory: "256Mi"
